<?php 
    session_start();
    unset($_SESSION["customer"]);
    //session_unset($_SESSION["customer"]);
    //session_destroy($_SESSION["customer"]);
    //destroy($_SESSION["customer"]);
    header('location:login.php');
    //exit();
?>